### ISSUE TITLE
Support addr:place= tagging scheme

### ISSUE THREAD

**Issue by ltog** [ltog/osmi-addresses#15]
Sometimes addr:place is used for addresses which are not assigned to a street but to a place (tagged with place=... and name=...).

We should support the addr:place= tagging scheme in two phases:

1. ~~Do not give an "No addr:street tag" error in this case since "addr:street=" is supposed to be deleted if "addr:place=" is used.~~ Done. See https://github.com/ltog/osmi-addresses/issues/14

2. Look in surrounding places (tagged with place=... and name=...) if the appropriate place can be found and if yes, draw a connection line. If it can't be found then this should be marked as an error.

See:
* http://wiki.openstreetmap.org/wiki/Key:addr:place
* http://wiki.openstreetmap.org/wiki/Key:place

**Comment by stephan75** [comment]
Hello @ltog , new year, new luck?
As I watched some activity on yours on github, may I kindly ask about this feature request?
I browsed through all open github issues, and from end-user view, maybe this one is a not-very-high-effort task?
Can we give some support to you for solving this?

**Comment by ltog** [comment]
Hello @stephan75!

> new year, new luck?

Yeah, I wanted to use the Holidays to work on new things in osmi-addresses. I did a lot of (uncommited) work on a prototype to implement some multi-threaded code that should speed things up (but won't bring user-visible changes). All commits/issues you see are actually preparations to bring this to life.

> maybe this one is a not-very-high-effort task?

I would rate the needed effort as moderate. Since I work on this in my spare time, that could still mean it will take months until it will run on the Geofabrik server... :-\

> Can we give some support to you for solving this?

Thanks for the offer! :-)

It depends a bit if you can (or would like to learn to) write code. That of course would be most helpful. I would also be willing to assist/explain so you can get into the code.

If that is not an option there is not so much to be done: One small thing would be to look up some examples where `addr:place=...` is actually used to then check if the software works. Such examples may be needed also in other issues. It would be helpful if you (or anybody else) would collect them. Some issues might need some other additional information. And you are of course welcome to add new issues if you find bugs or have ideas for new (thematically suitable) features.

Best regards!

PS: I don't recognize your nickname. Have we met?

**Comment by stephan75** [comment]
I am quite sure that we have not met yet, but see OSM forum, OSM wiki, help.osm.org, Wochennotiz, etc.

but nevertheless:

I am planning / scheduling a new Wochenaufgabe (weekly task) about missing addr:street.
See a draft on https://wiki.openstreetmap.org/wiki/User:Stephan75
(This text is going to be deleted after publishing the Wochenaufgabe)
There is an overpass-turbo query about addr-errors I am aiming at.
So that can be a basis for getting new or enhanced features to OSM inspector.

Unfortunately I have almost no programming skills,
but maybe I can give hints.
Can you guide me to the code inside osmi-addresses where objects are filtered and found that have no addr:street ?

**Comment by ltog** [comment]
Thanks for the link to your user page. Do you aim at fixing specific errors or is the goal a general improvement of quality/quantity of address data?

Does the Wochenaufgabe already have a target publication date? Implementing and deploying this feature is certainly possible but will take time. (Deployment would probably be done by @woodpeck.)

When I was writing my thesis about osmi-addresses (see https://github.com/ltog/osmi-addresses/blob/master/doc/report.pdf ), I described (among others) the following services:

- http://gulp21.bplaced.net/osm/housenumbervalidator/
- http://qa.poole.ch/

Are you aware of them?

**Comment by ltog** [comment]
Here's a draft on how to implement this:

- `FirstHandler`
  - Create new struct `place_lookup_type` (similar to `highway_lookup_type`) that contains:
    - coordinates of the places node/way's centroid
    - way/node ID
    - lastchange
  - Create new multimaps (nody and wayy) that maps from placename to structs
  - Read Nodes with `place=...` and `name=...` into struct and this into multimap
  - Read Ways with `place=...` and `name=...` then calculate centroid and write into struct and this into multimap
- `SecondHandler`
  - Extend `WaysWithAddressesWriter` to also write buildings tagged with `addr:place=...`
  - Extend `ConnectionLinePreprocessor` (methods `process_node()` and `process_way()`) to also read nodes and ways with `addr:place=...` set ; Call method `handle_connection_line()`
    - Call `ConnectionLineWriter.write_line()`
    - Create/call class `NearestPlaceWriter`

This draft is to be adjusted...

**Comment by stephan75** [comment]
I will have a closer look later today about your additions.

Maybe lets talk about Wochenaufgabe via osm.org messaging system. My username is same like here on github.

**Comment by ltog** [comment]
@stephan75 : I sent you a message...

**Comment by ltog** [comment]
QGIS-Filter for MapServer Filter expression at https://github.com/ltog/osmi-addresses/blob/a463b2b8f3b0a75d3870013eb17c60b9c96c2b7c/mapserver/addresses.map#L846 :

    is_ip=0 AND street!='' AND road_id=''

**Comment by ltog** [comment]
Next step: Adjust the file `mapserver/addresses.map` to show referenced but non-existing place=... .
