### ISSUE TITLE
Mark `addr:*=...` on non-closed ways

### ISSUE THREAD

**Issue by ltog** [ltog/osmi-addresses#70]
I can't think of a legitimate use where a `addr:street`, `addr:housenumber`, `addr:place`, etc. would be put on a non-closed way. Maybe we should mark these as suspicious/errors?

**Step 1:** Create an Overpass query to find such non-closed ways. (How do you find these? I asked at http://forum.openstreetmap.org/viewtopic.php?pid=571314 )
**Step 2:** Decide if displaying such ways would be useful.
**Step 3:** Implement.

**Comment by mmd-osm** [comment]
Finding closed or non-closed ways is currently not yet supported by Overpass API, see this issue: https://github.com/drolbr/Overpass-API/issues/197

**Comment by ltog** [comment]
@mmd-osm: Thank you for you reply! :-)

**Comment by ltog** [comment]
This should probably get its own SQLite file.

Checking if a `osmium::Way` is closed can be done with method `is_closed()`.

**Comment by ltog** [comment]
Here's an example: http://tools.geofabrik.de/osmi/?view=addresses&lon=-101.05367&lat=39.36663&zoom=14&overlays=addrx_on_nonclosed_way = https://www.openstreetmap.org/way/13360994
