### ISSUE TITLE
Mark suspicious house numbers

### ISSUE THREAD

**Issue by ltog** [ltog/osmi-addresses#84]
Basically everything except numbers and letters in a house number is suspicious. Example:

http://tools.geofabrik.de/osmi/?view=addresses&lon=8.83320&lat=47.23168&zoom=18&overlays=buildings,buildings_with_addresses,postal_code,entrances_deprecated,entrances,no_addr_street,street_not_found,nodes_with_addresses_defined,nodes_with_addresses_interpolated,interpolation,interpolation_errors,connection_lines,nearest_points,nearest_roads,nearest_areas

(multiple housenumbers separated by comma)

**Comment by ltog** [comment]
Here's an example with a `/`: https://www.openstreetmap.org/way/232283028 Maybe we should add this character to the list of allowed ones?

**Comment by stephan75** [comment]
Maybe there are "legal" housenumbers in other countries where we indeed have these special characters. Thus not so strict as in central europe ...

**Comment by ltog** [comment]
@stephan75 : Yeah, that might be. Do you have any references? If there is more specific data I might think about implementing regional rules.

**Comment by stephan75** [comment]
I only found some country specific hints about addresses in general at http://wiki.openstreetmap.org/wiki/Addresses ...without diving in that deeply.

We would need an own investigation about that via the popular OSM channels I fear.

**Comment by ImreSamu** [comment]
for the "misformatted_housenumber" ..
Thank you for the new functions!

in Hungary  the allowed characters can contains '/'  and '-'    
and sometimes spaces but this is very rare ..

example
```
60
60 62/B
60/62 
60/62/A 
60/62/B 
60/62A 
60/62B 
60-62 
60-62/A 
60-62/B 
60-62B
```

example reference:  [Hungarian Postal Service Company](https://en.wikipedia.org/wiki/Magyar_Posta) presentation 2014  - page 4 
http://www.esrihu.hu/static/upload/site/esrihu-uc-2014-eloadasok/esrihu-uc-2014-magyar-posta.pdf

it is possible to add country specific validation rules ?

**Comment by ltog** [comment]
@ImreSamu : Thanks for the examples, that's very helpful. I will collect rules for different countries/regions at https://github.com/ltog/osmi-addresses/issues/93 . At the moment I don't know if and how osmi-addresses will support such regional rules. I will track progress under #92.

@stephan75 : Thanks for mentioning https://github.com/ltog/osmi-addresses/issues/93 , that's certainly a starting point. I'm hesitant to ask around for different rules as long as there is no support for #92, since I don't want to fuel unwarranted hopes.
